### ISSUE TITLE
Input peak bam files instead of fastq

### ISSUE THREAD

**Issue by c2b2pss** [rnakato/Churros#1]
Hi,

Is it possible to input processed bam files after peak calling into churros without having to use fastq ? Just wish to reduce time of analysis.

Thanks!

**Comment by rnakato** [comment]
Hi,
It's definitely included on the list of planned updates for Churros, but so far it does not accept BAM files as input. I will let you know here when it is included.

**Comment by rnakato** [comment]
Hi c2b2pss,
Churros has been updated to `v1.3.0` where BAM files can be used as input files.
https://churros.readthedocs.io/en/latest/content/StepbyStep.html#id9
